# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b80563a02acb053c666f69f5b882777514e4c955d0ebad375b0abad2d62f787f0829980e68df276ca8301d237b9809c6c4a14921d5bc21cfa2d05872c9f679c

test:
  secret_key_base: 339523e1b875668c20af1b5991f31239670b3b98e46142ec81d097fd5097b9f77c4ce2ef236435f10c16626be8a43141382b7d4dca1a0f93366a6a0139f3d494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
